### ISSUE TITLE
Docker multistage

### ISSUE THREAD

**Issue by elmalba** [riferrei/otel-with-golang#1]
Hi there,

 Why don't use docker build multistage, for example use first stage only to build app and second stage to run app with less privileges and in minimal linux because original dockerfile create  image with 1.05GB  and when you use multistage the new image have only 20.8MB and this is very good to upload to docker hub or other registry

my suggestion is change dockerfile to this file

https://github.com/elmalba/otel-with-golang/blob/main/Dockerfile

**Comment by riferrei** [comment]
Hi @elmalba,

I tried the sample you shared, and indeed, the final image's size ends up being around ˜20.MB. This is a good thing. However, the code didn't work as expected, as the `hello-app` microservice never fully started and made the API available for consumption. I haven't troubleshot further, but I would guess that the alpine layer may not have all the runtime requirements necessary to execute the instrumented code.

Happy to include this change in the code if you fix what is pending to make the API work.

Thanks,

— @riferrei
